### ISSUE TITLE
Gymnasium support?

### ISSUE THREAD

**Issue by MarcoMeter** [proroklab/popgym#11]
Hi @smorad 
are you planning on upgrading PopGym to the latest version of gymnasium? (ETA?)
Thanks

**Comment by smorad** [comment]
Hi Marco,

There is already a PR  (#8) but I wasn’t sure if more people were using the old gym or the new gym. I’ll try and merge this in the next week.

**Comment by smorad** [comment]
@MarcoMeter https://github.com/proroklab/popgym/pull/8 is merged. You can `git clone` and `pip install -e .` to get the latest version. I will update the pypi release shortly.

**Comment by MarcoMeter** [comment]
Gracias!
