### ISSUE TITLE
NameNotFound error when instantiating popgym environment

### ISSUE THREAD

**Issue by Horrible22232** [proroklab/popgym#14]
I'm encountering a `NameNotFound error` when trying to instantiate the `popgym-Blackjack-v0` environment using the `gym.make` function. Specifically, the error message reads:
"NameNotFound: Environment popgym-Blackjack doesn't exist. Did you mean: `Blackjack`?"
I'm following the example code provided in https://github.com/proroklab/popgym/blob/master/examples/instantiate_env.py, which suggests that `popgym-Blackjack-v0` should be a valid environment.

The colab test code:
https://colab.research.google.com/drive/1lMwbjGFDaSZs0xxtrMq6D1gUfUV9a-C7?usp=sharing

**Comment by smorad** [comment]
@Horrible22232 sorry, blackjack is not a valid environment. I ended up removing for two reasons:

1. I was not confident it was free of bugs
2. The expected return of a blackjack player counting cards is ~1% greater than that of a player not counting cards. RL is so noisy that it would be impossible to tell if the agents were successfully counting cards.

[Higher-lower](https://github.com/proroklab/popgym/blob/master/popgym/envs/higher_lower.py#L21) is probably the closest environment to blackjack, where the expected return via card counting is a bit more noticeable (though still nearly imperceptible).

The [environment quickstart](https://popgym.readthedocs.io/en/latest/environment_quickstart.html) should get you started on the other environments.

**Comment by Horrible22232** [comment]
I was trying your other environments: `popgym-HigherLowerEasy-v0` and `popgym-StatelessCartPoleEasy-v0`. The error still remains the same.

**Comment by Horrible22232** [comment]
Thank you!
Now it works fine.
