### ISSUE TITLE
Question on Stateless environments

### ISSUE THREAD

**Issue by twni2016** [proroklab/popgym#20]
Hi authors,

In your paper, you said StatelessCartpole and StatelessPendulum are tasks that remove positions. But checking your code (e.g. https://github.com/proroklab/popgym/blob/master/popgym/envs/stateless_cartpole.py#L64), I think instead your task removes velocities. Is this a typo in your paper?

**Comment by smorad** [comment]
Yes, this is a typo. Thanks for catching it. We are slowly preparing an update to the Arxiv version, and we will add this to the to-do list.
