### ISSUE TITLE
Training details

### ISSUE THREAD

**Issue by twni2016** [proroklab/popgym#21]
I am wondering the sample efficiency of the algorithms from the learning curves plots (e.g. Fig. 10). How many transitions correspond to a `Epoch` in the plot? Does it depend on max_episode_length? 

In addition, just to confirm, are you using the max_episode_length as the context length of memory-based PPO algorithm?

**Comment by smorad** [comment]
Hi,

We list all the hyperparameters in the paper, see Table 2 in the appendix: https://arxiv.org/pdf/2303.01859.pdf

We use a minibatch size of 8192 (8 minibatches per batch, for 65536 transitions per batch) and 30 SGD iterations per epoch. So this is essentially 240 calls to `forward` per epoch. We find that this is overkill for some tasks, but it generally works well across most tasks and provides pretty tight confidence intervals.

We set `max_episode_length` to be the longest of any of our environments (1024). I don't trust RLlib to correctly train on partial trajectories -- I suspect there might be an RLlib bug there. So it's better to leave them complete.

**Comment by smorad** [comment]
Although the paper is written using `rllib`, I would not recommend using it unless you are trying to replicate the results. I have found [torchrl](https://github.com/pytorch/rl) to be faster, cleaner, and less-buggy. @vmoens recently added a tutorial for recurrent DQN.

**Comment by twni2016** [comment]
Thanks, but this does not directly answer my question. I wondered how many `env.step` calls per epoch or `forward`? I have my codebase for some RL algorithms so I will probably just take this sample complexity as a reference of task difficulties.

**Comment by smorad** [comment]
We call `env.step` 65536 times per epoch.
