### ISSUE TITLE
Observation preprocessing

### ISSUE THREAD

**Issue by hrpan** [proroklab/popgym#30]
Firstly, thanks for open sourcing this dedicated library for POMDPs!

In the baseline code I found the following:

    def wrap(env: POPGymEnv) -> POPGymEnv:
        return wrappers.Antialias(wrappers.PreviousAction(env))

which does not seem to use the Flatten wrapper (also the Flatten wrapper does not work for envs like StatelessCartPole due to mixing of continuous and discrete spaces), so I was wondering what's the best practice for preprocessing the observation space to feed into the network, thanks!

**Comment by smorad** [comment]
RLlib does it's own handling of observation spaces so there is no need to flatten. With other libraries, the `Flatten` wrapper can be very helpful! [See the docs for an example](https://popgym.readthedocs.io/en/latest/environment_quickstart.html).

The current version appears to work with `Flatten` (at least for me). Perhaps you are using an older release? Note that the last release renamed `StatelessCartPole` to be more descriptive.

```python
>>> from popgym.wrappers import Antialias, Flatten, PreviousAction
>>> from popgym.envs import PositionOnlyCartPoleEasy
>>> wrapped = Flatten(Antialias(PreviousAction(PositionOnlyCartPoleEasy())))
>>> wrapped.observation_space
Box([-4.80000019 -0.41887903  0.          0.          0.          0.        ], [4.80000019 0.41887903 1.         1.         1.         1.        ], (6,), float64)
```

You can also try using the `flatten_observation` [method from Gymnasium](https://gymnasium.farama.org/main/_modules/gymnasium/wrappers/flatten_observation/) if you prefer not to use my wrapper.

**Comment by hrpan** [comment]
Turns out I was using a previous release, and updating to 1.0.4 solved the problem, thanks!
