### ISSUE TITLE
Porting to torchrl

### ISSUE THREAD

**Issue by maxweissenbacher** [proroklab/popgym#32]
Hi there!

I would be interested in testing a new rl architecture on the popgym environments in order to benchmark and compare against the benchmarks you've included in your paper. I have an implementation of the algorithm in [torchrl](https://github.com/pytorch/rl) (and tested the algorithm on some custom partially observable environments). Is popgym compatible with torchrl? If not, I would be interested in implementing a port / a torchrl environment wrapper to make it compatible!

Max

**Comment by smorad** [comment]
It should work out of the box, the popgym envs just follow the `gymnasium` spec (with some additions, for example exposing `state_space` and such). Let me know if you run into any issues!

**Comment by smorad** [comment]
@maxweissenbacher did you run into any issues?

**Comment by maxweissenbacher** [comment]
Hi @smorad , it all seems to be working! Thank you!
