### ISSUE TITLE
Denominator in Fast Autoregressive Transformer

### ISSUE THREAD

**Issue by maciejwolczyk** [proroklab/popgym#35]
Hi! Great work on a very interesting topic!

The [original fast autoregressive transformer paper](https://arxiv.org/pdf/2006.16236) includes the following formula for the output in the recurrent formulation of the transformer:

![image](https://github.com/proroklab/popgym/assets/9852093/3618b5f6-91b8-41fd-bfff-e6f69319d562)

The denominator here is just a dot product between Q and z_i. I cross-checked it with your implementation of the denominator:

https://github.com/proroklab/popgym/blob/d3ed90f8c25262b5669181e85e2e8a069f41dd6c/popgym/baselines/models/linear_attention.py#L93

If you consider only a single element for a moment (so disregarding dimensions b and t), then the einsum here computes the outer-product between Q and z_i and then sums over the last two dimensions. If I understand correctly, to implement the formula from the paper one would have to do the following:

```python
denominator = torch.einsum("bti, bti -> bt", Q, Z).reshape(B, T, 1) + 1e-5
```
Is my line of thinking here correct?

Here's a quick illustration of what I mean:
```python
A = np.arange(10)
B = np.arange(10)
# Inner product
np.sum(A * B) # Output: 285
np.einsum("i,i->", A, B) # Output: 285

# Outer product + sum
np.sum(A.reshape(-1, 1) * B.reshape(1, -1)) # Output: 2025
np.einsum("i,j->", A, B) # Output: 2025
```

**Comment by smorad** [comment]
Maybe I need glasses, but both equations you wrote look the same to me

```python
denominator = torch.einsum("bti, btl -> bt", Q, Z).reshape(B, T, 1) + 1e-5 
denominator = torch.einsum("bti, bti -> bt", Q, Z).reshape(B, T, 1) + 1e-5
```

**Comment by smorad** [comment]
Maybe I need glasses, but aren't both lines you pasted equivalent?

```python
denominator = torch.einsum("bti, btl -> bt", Q, Z).reshape(B, T, 1) + 1e-5 
denominator = torch.einsum("bti, bti -> bt", Q, Z).reshape(B, T, 1) + 1e-5
```

I think you swapped the `l -> i` in the einsum, but don't they eval to the same expression?

**Comment by smorad** [comment]
They indeed do not, good catch

```python
>>> A = torch.arange(3*4*5).reshape(3,4,5)
>>> torch.einsum("bti, btj -> bt", A, A)
tensor([[  100,  1225,  3600,  7225],
        [12100, 18225, 25600, 34225],
        [44100, 55225, 67600, 81225]])
>>> torch.einsum("bti, bti -> bt", A, A)
tensor([[   30,   255,   730,  1455],
        [ 2430,  3655,  5130,  6855],
        [ 8830, 11055, 13530, 16255]])
```
We should definitely be computing the dot product instead of the summed outer product. Do you want to put up a pull request to fix this?

**Comment by maciejwolczyk** [comment]
Thanks for the quick answer! And sorry for the confusion, the change is indeed difficult to see. I just opened a PR with a fix.

**Comment by smorad** [comment]
Thanks for the fix!
